#!/usr/bin/env python3
import minimalmodbus
import serial
import time

from datetime import datetime

now = datetime.now()
print("Wait ", now)
time.sleep(5)

instrument = minimalmodbus.Instrument('</dev/ttyXYZ>', 1)
instrument.serial.baudrate = 19200
instrument.serial.bytesize = 8
instrument.serial.parity = serial.PARITY_EVEN
instrument.serial.stopbits = 1
instrument.serial.timeout = 0.25
instrument.mode = minimalmodbus.MODE_RTU

now = datetime.now()
print("Start ", now)

#DISCRETES INPUT
ausgabe = instrument.read_bit(1,2)
print ("DI1", ausgabe)
ausgabe = instrument.read_bit(2,2)
print ("DI2", ausgabe)
ausgabe = instrument.read_bit(5,2)
print ("DI5", ausgabe)
ausgabe = instrument.read_bit(6,2)
print ("DI6", ausgabe)
ausgabe = instrument.read_bit(7,2)
print ("DI7", ausgabe)
ausgabe = instrument.read_bit(9,2)
print ("DI9", ausgabe)
ausgabe = instrument.read_bit(10,2)
print ("DI10", ausgabe)
ausgabe = instrument.read_bit(11,2)
print ("DI11", ausgabe)
ausgabe = instrument.read_bit(12,2)
print ("DI12", ausgabe)
ausgabe = instrument.read_bit(13,2)
print ("DI13", ausgabe)
ausgabe = instrument.read_bit(14,2)
print ("DI14", ausgabe)


#COILS
ausgabe = instrument.read_bit(2,1)
print ("C2", ausgabe)
ausgabe = instrument.read_bit(3,1)
print ("C3", ausgabe)
ausgabe = instrument.read_bit(4,1)
print ("C4", ausgabe)
ausgabe = instrument.read_bit(6,1)
print ("C6", ausgabe)
ausgabe = instrument.read_bit(7,1)
print ("C7", ausgabe)
ausgabe = instrument.read_bit(8,1)
print ("C8", ausgabe)
ausgabe = instrument.read_bit(9,1)
print ("C9", ausgabe)
ausgabe = instrument.read_bit(12,1)
print ("C12", ausgabe)
ausgabe = instrument.read_bit(13,1)
print ("C13", ausgabe)

#Input Register
ausgabe = instrument.read_register(6,0,4,True)
print ("IR6", ausgabe)
ausgabe = instrument.read_register(7,0,4,True)
print ("IR7", ausgabe)
ausgabe = instrument.read_register(8,0,4,True)
print ("IR8", ausgabe)
ausgabe = instrument.read_register(9,0,4,True)
print ("IR9", ausgabe)
ausgabe = instrument.read_register(10,0,4,True)
print ("IR10", ausgabe)
ausgabe = instrument.read_register(12,0,4,True)
print ("IR12", ausgabe)
ausgabe = instrument.read_register(13,0,4,True)
print ("IR13", ausgabe)
ausgabe = instrument.read_register(14,0,4,True)
print ("IR14", ausgabe)
ausgabe = instrument.read_register(15,0,4,True)
print ("IR15", ausgabe)
ausgabe = instrument.read_register(16,0,4,True)
print ("IR16", ausgabe)
ausgabe = instrument.read_register(17,0,4,True)
print ("IR17", ausgabe)
ausgabe = instrument.read_register(19,0,4,True)
print ("IR19", ausgabe)
ausgabe = instrument.read_register(20,0,4,True)
print ("IR20", ausgabe)
ausgabe = instrument.read_register(21,1,4,True)
print ("IR21", ausgabe)
ausgabe = instrument.read_register(22,1,4,True)
print ("IR22", ausgabe)
ausgabe = instrument.read_register(23,1,4,True)
print ("IR23", ausgabe)
ausgabe = instrument.read_register(24,1,4,True)
print ("IR24", ausgabe)
ausgabe = instrument.read_register(25,0,4,True)
print ("IR25", ausgabe)
ausgabe = instrument.read_register(26,0,4,True)
print ("IR26", ausgabe)
ausgabe = instrument.read_register(27,0,4,True)
print ("IR27", ausgabe)
ausgabe = instrument.read_register(36,0,4,True)
print ("IR36", ausgabe)


#Holding Register
ausgabe = instrument.read_register(0,0,3,True)
print ("HR0", ausgabe)
ausgabe = instrument.read_register(1,0,3,True)
print ("HR1", ausgabe)
ausgabe = instrument.read_register(8,0,3,True)
print ("HR8", ausgabe)
ausgabe = instrument.read_register(9,0,3,True)
print ("HR9", ausgabe)
ausgabe = instrument.read_register(10,0,3,True)
print ("HR10", ausgabe)
ausgabe = instrument.read_register(11,0,3,True)
print ("HR11", ausgabe)
ausgabe = instrument.read_register(15,0,3,True)
print ("HR15", ausgabe)
ausgabe = instrument.read_register(16,0,3,True)
print ("HR16", ausgabe)
ausgabe = instrument.read_register(17,0,3,True)
print ("HR17", ausgabe)
ausgabe = instrument.read_register(22,0,3,True)
print ("HR22", ausgabe)
ausgabe = instrument.read_register(23,0,3,True)
print ("HR23", ausgabe)
ausgabe = instrument.read_register(24,0,3,True)
print ("HR24", ausgabe)
ausgabe = instrument.read_register(25,0,3,True)
print ("HR25", ausgabe)
ausgabe = instrument.read_register(26,0,3,True)
print ("HR26", ausgabe)
ausgabe = instrument.read_register(27,0,3,True)
print ("HR27", ausgabe)
ausgabe = instrument.read_register(28,0,3,True)
print ("HR28", ausgabe)
ausgabe = instrument.read_register(31,0,3,True)
print ("HR31", ausgabe)




instrument.serial.close()
now = datetime.now()
print("Ende ", now)
